### ISSUE TITLE
The page doesn't fully load on the first open

### ISSUE THREAD

**Issue by suda** [gaia-charge/website#53]
When opening the site for the first time, it seems to load partially:
<img width="1464" alt="Screenshot 2024-07-14 at 11 00 48" src="https://github.com/user-attachments/assets/a9c42466-e587-4560-8ce1-812835ea98c0">
Once refreshed everything seems to be working. It might have something to do with detecting the language as the only parts that show up are ones that are not translated.

**Comment by emendelski** [comment]
@suda There were missing translations in en.json / es.json.

I fixed i18n also for:
* Carousel
* How To Start (problem cloud) #55 

What is needed from you:
* [ ] add translations for [testimonials](https://github.com/gaia-charge/website/blob/feature/cleanup/src/services/messages/en.json#L226-L237)
* [ ] add meaningful keys and translations for each item in [How To Start list](https://github.com/gaia-charge/website/blob/feature/cleanup/src/services/messages/en.json#L178-L191) and update appropriately list in [HowToStart.svelte](https://github.com/gaia-charge/website/blob/feature/cleanup/src/components/HowToStart.svelte#L6-L21)
