### ISSUE TITLE
The cookie banner seems to be broken a bit

### ISSUE THREAD

**Issue by suda** [gaia-charge/website#54]
1. The colors and size are off compared to the design:
<img width="608" alt="Screenshot 2024-07-14 at 11 03 43" src="https://github.com/user-attachments/assets/ed14a90a-e4e6-41e9-af5e-09751d06da27">

2. It's necessary to click accept/reject cookies twice to dismiss the dialog

**Comment by emendelski** [comment]
Poprawiłem 1 w ramach:  a98b923

Natomiast wydaje mi się, że to poniekąd błąd tego pluginu. Nie pozwalają na podpięcie się pod większą ilość eventów. Więc nie jestem w stanie wykryć, czy ktoś już wyraził zgodę czy nie. Widze, że nie jestem jedyny, który jest zdziwiony, że nie ma takiej obsługi: https://github.com/beyonk-group/gdpr-cookie-consent-banner/pull/67

**Comment by suda** [comment]
Awesome. I guess problem 2 is not that bad, we can wait until they fix it upstream 👍
