### ISSUE TITLE
Animated "problem cloud"

### ISSUE THREAD

**Issue by suda** [gaia-charge/website#55]
At the moment the cloud with list of problems is a static image:

![](https://gaiacharge.com/_app/immutable/assets/Cloud.Kp1II2h0.svg)

It should be done dynamically and:
* [ ] The text should be translatable
* [ ] Should be responsive to work well on mobile as well

**Comment by emendelski** [comment]
Updated. You can test it. Each bubble has a random rotation added. 
RWD is also added. I left the translation to you.

**Comment by suda** [comment]
Awesome! Looking great! 👍
