### ISSUE TITLE
Replace the HubSpot contact form with Pipedrive

### ISSUE THREAD

**Issue by suda** [gaia-charge/website#57]
The contact form is using the HubSpot forms at the moment but we should switch it to Pipedrive as well.

* [ ] Add form submission using [Pipdrive's standalone form](https://webforms.pipedrive.com/f/72moX2d3I5kKo6qKLYRPmCBRuSlQfrEVbV9IYYbZ8qljei7JSW8hIcBKlnfvgqgMGD)
* [ ] Merge Last and First name into a single Name field

**Comment by emendelski** [comment]
@suda I need a code snippet for this form: https://support.pipedrive.com/en/article/web-forms

**Comment by suda** [comment]
@emendelski here's the link to the form: https://webforms.pipedrive.com/f/72moX2d3I5kKo6qKLYRPmCBRuSlQfrEVbV9IYYbZ8qljei7JSW8hIcBKlnfvgqgMGD

and here is the embed snippet:

```
<div class="pipedriveWebForms" data-pd-webforms="https://webforms.pipedrive.com/f/72moX2d3I5kKo6qKLYRPmCBRuSlQfrEVbV9IYYbZ8qljei7JSW8hIcBKlnfvgqgMGD"><script src="https://webforms.pipedrive.com/f/loader"></script></div>
```

**Comment by emendelski** [comment]
@suda form added. Form requires custom styles as it is explained in PR.
